### ISSUE TITLE
Installation Instruction do not work

### ISSUE THREAD

**Issue by COLABORATI** [lorenwest/monitor-dashboard#39]
The installation instructions do not lead to a working example. I get several errors on startup, like e.g.:
```
0 verbose lifecycle app@0.0.0~start: CWD: /home/user/app
11 silly lifecycle app@0.0.0~start: Args: [ '-c', 'node src/ "monitor-dashboard"' ]
12 silly lifecycle app@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle app@0.0.0~start: Failed to exec start script
```
There is no "monitor-dashboard" that could be referenced in the app/src directory. So something must be wrong with the instructions. How can I get this to work? Thanks!

**Comment by COLABORATI** [comment]
When I cd into node_modules/node-monitor I can run `npm start monitor-dashboard` with a different result, it seems to work, but does not show any values in the browser (see other issue). How to make that start from my app dir?

**Comment by lorenwest** [comment]
This project is looking for a collaborator for issues like these. Pull requests welcome.
